### ISSUE TITLE
[Bug]: Brass block from AllTheOres not working on compacting drawers

### ISSUE THREAD

**Issue by M4RC0Sx** [AllTheMods/AllTheOres#58] opened 2024-08-13 20:48 UTC
### Possible Fixes

Yes

### Modpack Version

ATM10 - 0.30

### What happened?

The brass from alltheores only works in compacting drawers as ingots and nuggets. Blocks do not work like the other kind of ores.

**Comment by DaddyLongspoon** [comment] 2024-08-14 08:22
duplicate of[ AllTheMods/AllTheOres#59](https://github.com/AllTheMods/AllTheOres/issues/59)

**Closed as completed** 2024-09-21 11:00 UTC
Labels: Bug, Duplicate
